site_name: ReadAlong-Studio
repo_url: https://github.com/ReadAlongs/Studio
edit_uri: blob/main/docs/
site_description: "Documentation for the ReadAlong-Studio: Audiobook alignment for Indigenous languages"
copyright: Copyright ©2019-2025 David Huggins-Daines and National Research Council Canada
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.footer
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [readalongs]
extra:
  version:
    provider: mike
    default: stable
markdown_extensions:
  - mkdocs-click
  - admonition
  - def_list
nav:
  - Home: index.md
  - Start: start.md
  - Installation: installation.md
  - The Web App: web-app.md
  - CLI Guide: cli-guide.md
  - CLI reference: cli-ref.md
  - Output Realizations: outputs.md
  - Advanced Topics: advanced-use.md
  - Troubleshooting: troubleshooting.md
exclude_docs:
  Contributing.md
