name: Deploy docs
on:
  push:
    branches:
      - main
      - dev.ej/deploy-docs-test
jobs:
  docs:
    # Create latest docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to get the gh-pages branch
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies and Studio
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r docs/requirements.txt -e .
      - name: Setup doc deploy
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs with mike 🚀 (DRY RUN)
        run: |
          mike deploy --update-aliases dev latest
      - name: show the results of the mike deploy
        run: |
          git show --stat gh-pages
          git show gh-pages
