name: Deploy docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    # Create latest docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to push to the gh-pages branch
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to get the gh-pages branch
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies and Studio
        run: |
          pip install -e .[docs]
      - name: Setup doc deploy
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs with mike 🚀
        run: |
          mike deploy --push --update-aliases dev latest
