# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# To create a release:
#  - make sure readalongs/_version.py has the new version number
#  - create an annotated tag, e.g., run: git tag -a v1.2.3 -m"v1.2.3"
#  - push the tag, which will trigger this workflow to publish on PyPI and GitHub

name: Upload Python Package
on:
  push:
    tags:
      # Publish only actual releases, not dev/alpha/beta/rc tags
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  matrix-tests:
    uses: ./.github/workflows/matrix-tests.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs:
      - tests
      - matrix-tests
    permissions:
      contents: write  # allows creating a GitHub Release
      id-token: write  # allows signing the dists with Sigstore
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Check that VERSION in _version.py and the tag are consistent
        env:
          VERSION: ${{ github.ref_name }}
        shell: bash
        run: diff <(echo "VERSION = \"${VERSION#v}\"") <(head -1 readalongs/_version.py)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build
        run: python -m build --sdist --wheel

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@a5caf349bc536fbef3668a10ed7f5cd309a4b53d # v3.2.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # @v1.21.0
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          attestations: true

  deploy-docs:
    # Create latest docs
    runs-on: ubuntu-latest
    needs:
      - publish
    permissions:
      contents: write  # to push to the gh-pages branch
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # needed to get the gh-pages branch
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies and Studio
        run: |
          pip install -e .[docs]
      - name: Setup doc deploy
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs with mike 🚀
        run: |
          mike deploy --push --update-aliases ${{ github.ref_name }} stable latest
